#cloud-config
system_info:
  default_user:
    name: rocky
    gecos: RHEL Cloud User
    groups: [wheel, adm, systemd-journal]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
  distro: rhel
write_files:
  - content: ${private_rsa_key}
    owner: root:root
    path: /etc/ssh/htcondor.key
    permissions: "0644"
  - content: |
      ALLOW_WRITE = *
      ALLOW_READ = $(ALLOW_WRITE)
      ALLOW_NEGOTIATOR = $(ALLOW_WRITE)
      DAEMON_LIST = COLLECTOR, MASTER, NEGOTIATOR, SCHEDD
      FILESYSTEM_DOMAIN = ${domain_name}
      UID_DOMAIN = ${domain_name}
      TRUST_UID_DOMAIN = True
      SOFT_UID_DOMAIN = True
    owner: root:root
    path: /etc/condor/condor_config.local
    permissions: "0644"
  - content: |
      /data           /etc/auto.data          nfsvers=3
    owner: root:root
    path: /etc/auto.master.d/data.autofs
    permissions: "0644"
  - content: |
      share  -rw,hard,intr,nosuid,quota  ${nfs_server_ip}:/data/share
    owner: root:root
    path: /etc/auto.data
    permissions: "0644"
  - content: |
      Host *
          GSSAPIAuthentication yes
              ForwardX11Trusted yes
              SendEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
          SendEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
          SendEnv LC_IDENTIFICATION LC_ALL LANGUAGE
          SendEnv XMODIFIERS
          StrictHostKeyChecking no
          UserKnownHostsFile=/dev/null
    owner: root:root
    path: /etc/ssh/ssh_config
    permissions: "0644"
runcmd:
  - mkdir -p /data/share
  - chown rocky.rocky /data/share
  - [mv, /etc/ssh/htcondor.key, /home/rocky/.ssh/id_rsa]
  - chmod 0600 /home/rocky/.ssh/id_rsa
  - [chown, rocky.rocky, /home/rocky/.ssh/id_rsa]
